DROP TABLE IF EXISTS payment;

CREATE TABLE payment (
  id bigint primary key generated by default as identity,
  invoice_id bigint not null references invoice(id) on delete restrict,
  payment_date timestamp default now(),
  amount numeric(12,2) not null,
  method text not null, -- e.g. 'bank_transfer', 'cash', 'credit_card'
  note text
);

-- Seed data matching the screenshot
-- Note: Assuming invoice 2 and 3 exist. If not, this might fail or we should use existing invoice IDs.
-- The screenshot shows explicit IDs 1 and 2 for payments.
INSERT INTO payment (id, invoice_id, payment_date, amount, method, note)
VALUES
(1, 2, '2026-03-01 00:00:00', 1500.00, 'bank_transfer', NULL),
(2, 3, '2026-03-02 01:00:00', 3200.00, 'cash', NULL)
ON CONFLICT (id) DO UPDATE 
SET invoice_id = EXCLUDED.invoice_id,
    payment_date = EXCLUDED.payment_date,
    amount = EXCLUDED.amount,
    method = EXCLUDED.method,
    note = EXCLUDED.note;

-- Update sequence so next insert gets id 3
SELECT setval(pg_get_serial_sequence('payment', 'id'), COALESCE((SELECT MAX(id) FROM payment), 0) + 1, false);
