create table if not exists payment (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_id bigint not null references invoice(id) on delete restrict,
  amount numeric(12,2) not null,
  remark text
);
