\set ON_ERROR_STOP on

-- Migration: Add Sales Person table and column to Invoice
create table if not exists sales_person (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  start_work_date date
);

alter table invoice add column if not exists sales_person_id bigint references sales_person(id);

-- Seed Data for Sales Person
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (1, 'SP001', 'Alice Johnson', '2024-01-15') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (2, 'SP002', 'Bob Smith', '2024-02-01') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (3, 'SP003', 'Charlie Brown', '2024-03-10') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (4, 'SP004', 'David Wilson', '2024-04-20') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (5, 'SP005', 'Eva Green', '2024-05-05') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (6, 'SP006', 'Frank White', '2024-06-12') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (7, 'SP007', 'Grace Lee', '2024-07-25') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (8, 'SP008', 'Hannah Scott', '2024-08-30') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (9, 'SP009', 'Ian Clark', '2024-09-14') ON CONFLICT DO NOTHING;
INSERT INTO sales_person (id, code, name, start_work_date) VALUES (10, 'SP010', 'Jane Doe', '2024-10-01') ON CONFLICT DO NOTHING;

-- Update sequence
SELECT setval(pg_get_serial_sequence('sales_person', 'id'), coalesce(max(id),0) + 1, false) FROM sales_person;
